# 재실행❌

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# 세이 악성코드 이미지화 코드(주석.ver)
import os,sys
import numpy as np
from PIL import Image

def getBinaryData(filename):
  image=np.zeros((256,256)) ## 256사이즈만 받을 예정, 0으로 채운 256사이즈의 배열 만듦
  with open (filename) as file: ##C:\Users\ssh09\Desktop\0aSTGBVRXeJhx5OcpsgC.asm 이 파일경로를 파일로 가져오기
    rectype = np.dtype(np.int8) ## 부호 있는 8비트로 변환
    binaryValues = np.fromfile(file, dtype=rectype) ##binaryValues는 위의 변수 file을 8비트 파일로 변환한것

    i,j,p=0,0,0 ## image 채우기 위한 변수
    for c in binaryValues: ## image 채우기 위한 반복문 (binaryValues가 끝날때까지 binaryValues를 하나씩 c에 집어넣는 반복문)
        if(i<256):
            if(j<256):
                image[i][j]=c ## 2차원 배열로 만들어 점 찍기
                j+=1
            elif(j==256):
                j=0
                i+=1
        elif(i==256):
            i=0

    print(image)
    return image ## 점찍은 배열을 리턴

def createGreyScaleImageSpecificWith(dataSet, outputfilename):  ## dataSet에는 위의 리턴 값 image가 들어가있음

  img=Image.fromarray(dataSet) ##넘파이배열로 돼있는 이미지배열을 PIL이미지로 변환
  img2= img.convert('L') ## L은 그레이스케일로


  imagename = outputfilename + ".png"
  img2.save(imagename)

  ##img2=img2.resize((256,256),Image.ANTIALIAS) ##resize시 깨지지 않게 저장해주는 인자 (Image.ANTIALIAS)

  img2.show()
  print(imagename+" Greyscale image created")

if __name__ == "__main__":
    file_folder = "/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/raw_asm_data"
    output_folder = "/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img"


    files = os.listdir(file_folder)
    i=1
    for file_name in files:
        file_path = os.path.join(file_folder, file_name)
        output_path = os.path.join(output_folder, os.path.splitext(file_name)[0])

        binary_data = getBinaryData(file_path)
        createGreyScaleImageSpecificWith(binary_data, output_path)
        print(i,'개 진행함')
        i += 1

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [ 46. 100.  97. ...  32.  32.  56.]
 [104.  32.  59. ...  32.  32.  32.]
 [ 32. 100.  98. ...   9.  32.  32.]]
/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img/gIONM8E513LYstAjyzWl.png Greyscale image created
1046 개 진행함
[[ 51.  50.  50. ...   9.   9.  32.]
 [ 32.  32.  32. ...  10.  46. 100.]
 [116.  97.  58. ...  48.   9.   9.]
 ...
 [ 48.  13.  10. ...  50.  50.  67.]
 [ 32.  48.  48. ...  32.  32.  32.]
 [100.  98.  32. ...  97.  58.  48.]]
/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img/9CYFq8BMeELSXsZ7Ubpx.png Greyscale image created
1047 개 진행함
[[ 48.  48.   9. ...   9.   9. 100.]
 [ 32.  32.  32. ... 114. 100.  97.]
 [ 97.  58.  48. ...  68.  52.   9.]
 ...
 [ 56.   9.  48. ...   9.   9.   9.]
 [100.  98.  32. ...  10.  46. 114.]
 [ 97. 116.  97. ...  50.  53.  66.]]
/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img/1GKhFnumAdIeykS3rZYi.png Greyscale image created
1048 개 진행함
[[ 48.

In [6]:
def count_files_in_directory(directory):
    files = os.listdir(directory)

    return len(files)

directory_path = "/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img"

file_count = count_files_in_directory(directory_path)
print(f"binary_img 폴더 내 파일 개수: {file_count}")

binary_img 폴더 내 파일 개수: 1601


raw_asm_data폴더에 있던 train_label_200.csv도 이미지화 되어버려서 그것만 임의로 삭제하였습니다!

In [7]:
def count_files_in_directory(directory):
    files = os.listdir(directory)

    return len(files)

directory_path = "/content/drive/MyDrive/Ping!_AI악성코드분류기/microsoft/binary_img"

file_count = count_files_in_directory(directory_path)
print(f"binary_img 폴더 내 파일 개수: {file_count}")

binary_img 폴더 내 파일 개수: 1600
